package config

import (
	"crypto/sha1" // nolint:gosec
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/infracost/config/cdk"
	"github.com/infracost/config/types"
)

const CurrentVersion = "0.3"

type ConfigBase struct {
	Version string `yaml:"version"`
}

type Config struct {
	ConfigBase    `yaml:",inline"`
	Currency      string     `yaml:"currency,omitempty"`
	UsageFilePath string     `yaml:"usage_file,omitempty"`
	Terraform     Terraform  `yaml:"terraform,omitempty"`
	Projects      []*Project `yaml:"projects"`
	CDK           cdk.Config `yaml:"cdk,omitempty"`
	// Plugins holds repo-level, plugin-specific defaults keyed by the consuming plugin name (e.g.
	// "terraform"). Opaque to config - the plugin that matches the key owns the schema. It is NOT
	// serialized directly (yaml:"-"): (Un)MarshalYAML route through the configfile layer so each blob
	// lives under its own heading rather than a `plugins:` block.
	Plugins map[string]map[string]any `yaml:"-"`
}

type Terraform struct {
	// Deprecated: set the regex source map per-project under plugins.terraform.regexSourceMap instead.
	// Still read for backwards compatibility (folded into each terraform project's plugins blob on
	// load); no longer written by config generation.
	SourceMap []TerraformRegexSource `yaml:"source_map,omitempty"`
	Defaults  TerraformDefaults      `yaml:"defaults,omitempty"`
}

type TerraformDefaults struct {
	Cloud     TerraformCloud `yaml:"cloud,omitempty"`
	Spacelift Spacelift      `yaml:"spacelift,omitempty"`
	Workspace string         `yaml:"workspace,omitempty"`
}

// TerraformCloud is the authoring surface for Terraform Cloud / Enterprise. It is NOT deprecated and
// NOT folded into the plugins blob: Host/Org/Workspace are caller-sourced and read outside the plugin
// (the caller passes them to the plugin via GenericOptions.TerraformCloudConfiguration, and reads the
// host to build the terraform-cloud credential set). The token is a credential supplied here or via
// INFRACOST_TERRAFORM_CLOUD_TOKEN and travels via GenericOptions.CredentialSets.
type TerraformCloud struct {
	Host      string `yaml:"host,omitempty"`
	Org       string `yaml:"org,omitempty"`
	Workspace string `yaml:"workspace,omitempty"`
	Token     string `yaml:"token,omitempty"`
}

type Spacelift struct {
	APIKey SpaceliftAPIKey `yaml:"api_key"`
}

type SpaceliftAPIKey struct {
	Endpoint string `yaml:"endpoint,omitempty"`
	ID       string `yaml:"id,omitempty"`
	Secret   string `yaml:"secret,omitempty"`
}

type ProjectTerraform struct {
	Cloud     TerraformCloud `yaml:"cloud,omitempty"`
	Spacelift Spacelift      `yaml:"spacelift,omitempty"`
	// Deprecated: read the vars from the plugins blob (Project.Plugins["terraform"]["vars"]) instead.
	// Populated on load as a backwards-compat mirror of that blob (the canonical source, and the only
	// representation serialized); not read by config itself.
	Vars map[string]any `yaml:"vars,omitempty"`
	// Deprecated: read the var files from the plugins blob (Project.Plugins["terraform"]["var_files"])
	// instead. Populated on load as a backwards-compat mirror of that blob (the canonical source, and
	// the only representation serialized); not read by config itself.
	VarFiles []string `yaml:"var_files,omitempty"`
	// Workspace is the terraform workspace to select. It is NOT part of the plugins blob: it is a
	// caller-sourced runtime option passed to the plugin via GenericOptions.Workspace, and is also read
	// outside the plugin (the project's workspace in the cost output / provider input). It stays a
	// top-level field and is still written by generation.
	Workspace string `yaml:"workspace,omitempty"`
}

// Project defines a specific terraform project config. This can be used
// specify per folder/project configurations. Fields are documented below.
// More info is outlined here: https://www.infracost.io/config-file
type Project struct {
	Name            string            `yaml:"name,omitempty"`
	Type            ProjectType       `yaml:"type,omitempty"` // terraform, terragrunt
	Path            string            `yaml:"path"`
	Terraform       ProjectTerraform  `yaml:"terraform,omitempty"`
	Env             map[string]string `yaml:"env,omitempty"`
	Metadata        map[string]string `yaml:"metadata,omitempty"`
	EnvName         string            `yaml:"env_name,omitempty"`
	UsageFile       string            `yaml:"usage_file,omitempty"`
	YorConfigPath   string            `yaml:"yor_config_path,omitempty"`
	ExcludePaths    []string          `yaml:"exclude_paths,omitempty"`
	DependencyPaths []string          `yaml:"dependency_paths,omitempty"`
	AWS             ProjectAWSConfig  `yaml:"aws,omitempty"`
	CDKSynthError   string            `yaml:"cdk_synth_error,omitempty"`
	// Plugins holds plugin-specific parse options keyed by the consuming plugin name (e.g.
	// "terraform"). It is the persisted raw_options blob - autogenerated during identification and
	// user-editable. Opaque to config; the plugin that matches the key owns the schema. NOT serialized
	// directly (yaml:"-"): the configfile layer splits/merges it under the project's headings
	// (terraform:, aws:, ...) rather than a `plugins:` block.
	Plugins map[string]map[string]any `yaml:"-"`
}

// ConfigSHA computes a deterministic SHA for the project config based on its
// key fields. This is used by the dashboard to detect config changes and
// deduplicate breakdowns.
func (p *Project) ConfigSHA() string {
	var inputs []string
	inputs = append(inputs, p.Name)
	inputs = append(inputs, p.Path)
	inputs = append(inputs, p.ExcludePaths...)
	inputs = append(inputs, p.DependencyPaths...)
	// Terraform.Vars/VarFiles are backwards-compat mirrors of the Plugins blob (hashed below), so
	// they are deliberately NOT hashed here - that would double-count them.
	inputs = append(inputs, p.Terraform.Workspace)
	inputs = append(inputs, p.Terraform.Cloud.Host)
	inputs = append(inputs, p.Terraform.Cloud.Org)
	inputs = append(inputs, p.Terraform.Cloud.Workspace)
	inputs = append(inputs, p.Terraform.Cloud.Token)
	inputs = append(inputs, p.UsageFile)
	inputs = append(inputs, p.Terraform.Spacelift.APIKey.Endpoint)
	inputs = append(inputs, p.Terraform.Spacelift.APIKey.ID)
	inputs = append(inputs, p.Terraform.Spacelift.APIKey.Secret)
	orderEnv := make([]string, 0, len(p.Env))
	for k, v := range p.Env {
		orderEnv = append(orderEnv, fmt.Sprintf("%s=%s", k, v))
	}
	sort.Strings(orderEnv)
	inputs = append(inputs, orderEnv...)

	// Include the plugin blobs so the sha reflects options that now live only under plugins.<name>:
	// generated configs no longer write the deprecated terraform.* fields, so without this the sha
	// would miss var-file/workspace changes for them. json.Marshal sorts map keys, so this is
	// deterministic.
	if len(p.Plugins) > 0 {
		if b, err := json.Marshal(p.Plugins); err == nil {
			inputs = append(inputs, string(b))
		}
	}

	// nolint:gosec
	gen := sha1.New()
	_, _ = gen.Write([]byte(strings.Join(inputs, "|")))
	return hex.EncodeToString(gen.Sum(nil))
}

// ProjectAWSConfig is the deprecated typed view of the cloudformation aws context. The canonical
// representation is the plugins blob Project.Plugins["cloudformation"] (flat snake_case keys: region,
// account_id, stack_id, stack_name). These fields are populated on load as a backwards-compat mirror
// of that blob; prefer reading the blob. Config itself does not read them.
type ProjectAWSConfig struct {
	Region    string `yaml:"region,omitempty"`
	StackID   string `yaml:"stack_id,omitempty"`
	StackName string `yaml:"stack_name,omitempty"`
	AccountID string `yaml:"account_id,omitempty"`
}

// ProjectType is aliased to types.ProjectType so the canonical definition can
// live in a child-importable package while existing consumers of
// config.ProjectType keep compiling unchanged.
type ProjectType = types.ProjectType

const (
	ProjectTypeUnknown        = types.ProjectTypeUnknown
	ProjectTypeTerraform      = types.ProjectTypeTerraform
	ProjectTypeTerragrunt     = types.ProjectTypeTerragrunt
	ProjectTypeCloudFormation = types.ProjectTypeCloudFormation
	ProjectTypeCDKTypeScript  = types.ProjectTypeCDKTypeScript
	ProjectTypeCDKJavaScript  = types.ProjectTypeCDKJavaScript
	ProjectTypeCDKPython      = types.ProjectTypeCDKPython
	ProjectTypeCiscoStacks    = types.ProjectTypeCiscoStacks
)

type AWSCredentials struct {
	AccessKeyID     string
	SecretAccessKey string
	AccessToken     string
	Region          string
}

func defaultConfig() *Config {
	return &Config{
		ConfigBase: ConfigBase{
			Version: CurrentVersion,
		},
		Currency: "USD",
		Projects: []*Project{{
			Path: ".",
		}},
	}
}

func (c *Config) Clone() *Config {
	if c == nil {
		return nil
	}
	clone := *c
	return &clone
}
